
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Settlement: 'Settlement',
  Settler: 'Settler'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  password: 'password',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const SettlementScalarFieldEnum = {
  id: 'id',
  ownerId: 'ownerId',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SettlementScalarFieldEnum = (typeof SettlementScalarFieldEnum)[keyof typeof SettlementScalarFieldEnum]


export const SettlerScalarFieldEnum = {
  id: 'id',
  settlementId: 'settlementId',
  name: 'name',
  health_pain: 'health_pain',
  health_infection: 'health_infection',
  health_digestion: 'health_digestion',
  health_consciousness: 'health_consciousness',
  health_sanity: 'health_sanity',
  capacity_breathing: 'capacity_breathing',
  capacity_eating: 'capacity_eating',
  capacity_hearing: 'capacity_hearing',
  capacity_moving: 'capacity_moving',
  capacity_seeing: 'capacity_seeing',
  needs_thirst: 'needs_thirst',
  needs_hunger: 'needs_hunger',
  needs_sleep: 'needs_sleep',
  needs_rest: 'needs_rest',
  needs_social: 'needs_social',
  attr_strength: 'attr_strength',
  attr_constitution: 'attr_constitution',
  attr_dexterity: 'attr_dexterity',
  attr_perception: 'attr_perception',
  attr_intelligence: 'attr_intelligence',
  attr_wisdom: 'attr_wisdom',
  skill_digging: 'skill_digging',
  skill_logging: 'skill_logging',
  skill_mining: 'skill_mining',
  skill_foraging: 'skill_foraging',
  skill_fishing: 'skill_fishing',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SettlerScalarFieldEnum = (typeof SettlerScalarFieldEnum)[keyof typeof SettlerScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]

