
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Settler` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Settler
 * 
 */
export type SettlerModel = runtime.Types.Result.DefaultSelection<Prisma.$SettlerPayload>

export type AggregateSettler = {
  _count: SettlerCountAggregateOutputType | null
  _avg: SettlerAvgAggregateOutputType | null
  _sum: SettlerSumAggregateOutputType | null
  _min: SettlerMinAggregateOutputType | null
  _max: SettlerMaxAggregateOutputType | null
}

export type SettlerAvgAggregateOutputType = {
  health_pain: number | null
  health_infection: number | null
  health_digestion: number | null
  health_consciousness: number | null
  health_sanity: number | null
  capacity_breathing: number | null
  capacity_eating: number | null
  capacity_hearing: number | null
  capacity_moving: number | null
  capacity_seeing: number | null
  needs_thirst: number | null
  needs_hunger: number | null
  needs_sleep: number | null
  needs_rest: number | null
  needs_social: number | null
  attr_strength: number | null
  attr_constitution: number | null
  attr_dexterity: number | null
  attr_perception: number | null
  attr_intelligence: number | null
  attr_wisdom: number | null
  skill_digging: number | null
  skill_logging: number | null
  skill_mining: number | null
  skill_foraging: number | null
  skill_fishing: number | null
}

export type SettlerSumAggregateOutputType = {
  health_pain: number | null
  health_infection: number | null
  health_digestion: number | null
  health_consciousness: number | null
  health_sanity: number | null
  capacity_breathing: number | null
  capacity_eating: number | null
  capacity_hearing: number | null
  capacity_moving: number | null
  capacity_seeing: number | null
  needs_thirst: number | null
  needs_hunger: number | null
  needs_sleep: number | null
  needs_rest: number | null
  needs_social: number | null
  attr_strength: number | null
  attr_constitution: number | null
  attr_dexterity: number | null
  attr_perception: number | null
  attr_intelligence: number | null
  attr_wisdom: number | null
  skill_digging: number | null
  skill_logging: number | null
  skill_mining: number | null
  skill_foraging: number | null
  skill_fishing: number | null
}

export type SettlerMinAggregateOutputType = {
  id: string | null
  settlementId: string | null
  name: string | null
  health_pain: number | null
  health_infection: number | null
  health_digestion: number | null
  health_consciousness: number | null
  health_sanity: number | null
  capacity_breathing: number | null
  capacity_eating: number | null
  capacity_hearing: number | null
  capacity_moving: number | null
  capacity_seeing: number | null
  needs_thirst: number | null
  needs_hunger: number | null
  needs_sleep: number | null
  needs_rest: number | null
  needs_social: number | null
  attr_strength: number | null
  attr_constitution: number | null
  attr_dexterity: number | null
  attr_perception: number | null
  attr_intelligence: number | null
  attr_wisdom: number | null
  skill_digging: number | null
  skill_logging: number | null
  skill_mining: number | null
  skill_foraging: number | null
  skill_fishing: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SettlerMaxAggregateOutputType = {
  id: string | null
  settlementId: string | null
  name: string | null
  health_pain: number | null
  health_infection: number | null
  health_digestion: number | null
  health_consciousness: number | null
  health_sanity: number | null
  capacity_breathing: number | null
  capacity_eating: number | null
  capacity_hearing: number | null
  capacity_moving: number | null
  capacity_seeing: number | null
  needs_thirst: number | null
  needs_hunger: number | null
  needs_sleep: number | null
  needs_rest: number | null
  needs_social: number | null
  attr_strength: number | null
  attr_constitution: number | null
  attr_dexterity: number | null
  attr_perception: number | null
  attr_intelligence: number | null
  attr_wisdom: number | null
  skill_digging: number | null
  skill_logging: number | null
  skill_mining: number | null
  skill_foraging: number | null
  skill_fishing: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SettlerCountAggregateOutputType = {
  id: number
  settlementId: number
  name: number
  health_pain: number
  health_infection: number
  health_digestion: number
  health_consciousness: number
  health_sanity: number
  capacity_breathing: number
  capacity_eating: number
  capacity_hearing: number
  capacity_moving: number
  capacity_seeing: number
  needs_thirst: number
  needs_hunger: number
  needs_sleep: number
  needs_rest: number
  needs_social: number
  attr_strength: number
  attr_constitution: number
  attr_dexterity: number
  attr_perception: number
  attr_intelligence: number
  attr_wisdom: number
  skill_digging: number
  skill_logging: number
  skill_mining: number
  skill_foraging: number
  skill_fishing: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type SettlerAvgAggregateInputType = {
  health_pain?: true
  health_infection?: true
  health_digestion?: true
  health_consciousness?: true
  health_sanity?: true
  capacity_breathing?: true
  capacity_eating?: true
  capacity_hearing?: true
  capacity_moving?: true
  capacity_seeing?: true
  needs_thirst?: true
  needs_hunger?: true
  needs_sleep?: true
  needs_rest?: true
  needs_social?: true
  attr_strength?: true
  attr_constitution?: true
  attr_dexterity?: true
  attr_perception?: true
  attr_intelligence?: true
  attr_wisdom?: true
  skill_digging?: true
  skill_logging?: true
  skill_mining?: true
  skill_foraging?: true
  skill_fishing?: true
}

export type SettlerSumAggregateInputType = {
  health_pain?: true
  health_infection?: true
  health_digestion?: true
  health_consciousness?: true
  health_sanity?: true
  capacity_breathing?: true
  capacity_eating?: true
  capacity_hearing?: true
  capacity_moving?: true
  capacity_seeing?: true
  needs_thirst?: true
  needs_hunger?: true
  needs_sleep?: true
  needs_rest?: true
  needs_social?: true
  attr_strength?: true
  attr_constitution?: true
  attr_dexterity?: true
  attr_perception?: true
  attr_intelligence?: true
  attr_wisdom?: true
  skill_digging?: true
  skill_logging?: true
  skill_mining?: true
  skill_foraging?: true
  skill_fishing?: true
}

export type SettlerMinAggregateInputType = {
  id?: true
  settlementId?: true
  name?: true
  health_pain?: true
  health_infection?: true
  health_digestion?: true
  health_consciousness?: true
  health_sanity?: true
  capacity_breathing?: true
  capacity_eating?: true
  capacity_hearing?: true
  capacity_moving?: true
  capacity_seeing?: true
  needs_thirst?: true
  needs_hunger?: true
  needs_sleep?: true
  needs_rest?: true
  needs_social?: true
  attr_strength?: true
  attr_constitution?: true
  attr_dexterity?: true
  attr_perception?: true
  attr_intelligence?: true
  attr_wisdom?: true
  skill_digging?: true
  skill_logging?: true
  skill_mining?: true
  skill_foraging?: true
  skill_fishing?: true
  createdAt?: true
  updatedAt?: true
}

export type SettlerMaxAggregateInputType = {
  id?: true
  settlementId?: true
  name?: true
  health_pain?: true
  health_infection?: true
  health_digestion?: true
  health_consciousness?: true
  health_sanity?: true
  capacity_breathing?: true
  capacity_eating?: true
  capacity_hearing?: true
  capacity_moving?: true
  capacity_seeing?: true
  needs_thirst?: true
  needs_hunger?: true
  needs_sleep?: true
  needs_rest?: true
  needs_social?: true
  attr_strength?: true
  attr_constitution?: true
  attr_dexterity?: true
  attr_perception?: true
  attr_intelligence?: true
  attr_wisdom?: true
  skill_digging?: true
  skill_logging?: true
  skill_mining?: true
  skill_foraging?: true
  skill_fishing?: true
  createdAt?: true
  updatedAt?: true
}

export type SettlerCountAggregateInputType = {
  id?: true
  settlementId?: true
  name?: true
  health_pain?: true
  health_infection?: true
  health_digestion?: true
  health_consciousness?: true
  health_sanity?: true
  capacity_breathing?: true
  capacity_eating?: true
  capacity_hearing?: true
  capacity_moving?: true
  capacity_seeing?: true
  needs_thirst?: true
  needs_hunger?: true
  needs_sleep?: true
  needs_rest?: true
  needs_social?: true
  attr_strength?: true
  attr_constitution?: true
  attr_dexterity?: true
  attr_perception?: true
  attr_intelligence?: true
  attr_wisdom?: true
  skill_digging?: true
  skill_logging?: true
  skill_mining?: true
  skill_foraging?: true
  skill_fishing?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type SettlerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Settler to aggregate.
   */
  where?: Prisma.SettlerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Settlers to fetch.
   */
  orderBy?: Prisma.SettlerOrderByWithRelationInput | Prisma.SettlerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SettlerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Settlers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Settlers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Settlers
  **/
  _count?: true | SettlerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SettlerAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SettlerSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SettlerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SettlerMaxAggregateInputType
}

export type GetSettlerAggregateType<T extends SettlerAggregateArgs> = {
      [P in keyof T & keyof AggregateSettler]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSettler[P]>
    : Prisma.GetScalarType<T[P], AggregateSettler[P]>
}




export type SettlerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SettlerWhereInput
  orderBy?: Prisma.SettlerOrderByWithAggregationInput | Prisma.SettlerOrderByWithAggregationInput[]
  by: Prisma.SettlerScalarFieldEnum[] | Prisma.SettlerScalarFieldEnum
  having?: Prisma.SettlerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SettlerCountAggregateInputType | true
  _avg?: SettlerAvgAggregateInputType
  _sum?: SettlerSumAggregateInputType
  _min?: SettlerMinAggregateInputType
  _max?: SettlerMaxAggregateInputType
}

export type SettlerGroupByOutputType = {
  id: string
  settlementId: string
  name: string
  health_pain: number
  health_infection: number
  health_digestion: number
  health_consciousness: number
  health_sanity: number
  capacity_breathing: number
  capacity_eating: number
  capacity_hearing: number
  capacity_moving: number
  capacity_seeing: number
  needs_thirst: number
  needs_hunger: number
  needs_sleep: number
  needs_rest: number
  needs_social: number
  attr_strength: number
  attr_constitution: number
  attr_dexterity: number
  attr_perception: number
  attr_intelligence: number
  attr_wisdom: number
  skill_digging: number
  skill_logging: number
  skill_mining: number
  skill_foraging: number
  skill_fishing: number
  createdAt: Date
  updatedAt: Date
  _count: SettlerCountAggregateOutputType | null
  _avg: SettlerAvgAggregateOutputType | null
  _sum: SettlerSumAggregateOutputType | null
  _min: SettlerMinAggregateOutputType | null
  _max: SettlerMaxAggregateOutputType | null
}

export type GetSettlerGroupByPayload<T extends SettlerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SettlerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SettlerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SettlerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SettlerGroupByOutputType[P]>
      }
    >
  >



export type SettlerWhereInput = {
  AND?: Prisma.SettlerWhereInput | Prisma.SettlerWhereInput[]
  OR?: Prisma.SettlerWhereInput[]
  NOT?: Prisma.SettlerWhereInput | Prisma.SettlerWhereInput[]
  id?: Prisma.StringFilter<"Settler"> | string
  settlementId?: Prisma.StringFilter<"Settler"> | string
  name?: Prisma.StringFilter<"Settler"> | string
  health_pain?: Prisma.IntFilter<"Settler"> | number
  health_infection?: Prisma.IntFilter<"Settler"> | number
  health_digestion?: Prisma.IntFilter<"Settler"> | number
  health_consciousness?: Prisma.IntFilter<"Settler"> | number
  health_sanity?: Prisma.IntFilter<"Settler"> | number
  capacity_breathing?: Prisma.IntFilter<"Settler"> | number
  capacity_eating?: Prisma.IntFilter<"Settler"> | number
  capacity_hearing?: Prisma.IntFilter<"Settler"> | number
  capacity_moving?: Prisma.IntFilter<"Settler"> | number
  capacity_seeing?: Prisma.IntFilter<"Settler"> | number
  needs_thirst?: Prisma.IntFilter<"Settler"> | number
  needs_hunger?: Prisma.IntFilter<"Settler"> | number
  needs_sleep?: Prisma.IntFilter<"Settler"> | number
  needs_rest?: Prisma.IntFilter<"Settler"> | number
  needs_social?: Prisma.IntFilter<"Settler"> | number
  attr_strength?: Prisma.IntFilter<"Settler"> | number
  attr_constitution?: Prisma.IntFilter<"Settler"> | number
  attr_dexterity?: Prisma.IntFilter<"Settler"> | number
  attr_perception?: Prisma.IntFilter<"Settler"> | number
  attr_intelligence?: Prisma.IntFilter<"Settler"> | number
  attr_wisdom?: Prisma.IntFilter<"Settler"> | number
  skill_digging?: Prisma.IntFilter<"Settler"> | number
  skill_logging?: Prisma.IntFilter<"Settler"> | number
  skill_mining?: Prisma.IntFilter<"Settler"> | number
  skill_foraging?: Prisma.IntFilter<"Settler"> | number
  skill_fishing?: Prisma.IntFilter<"Settler"> | number
  createdAt?: Prisma.DateTimeFilter<"Settler"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Settler"> | Date | string
  settlement?: Prisma.XOR<Prisma.SettlementScalarRelationFilter, Prisma.SettlementWhereInput>
}

export type SettlerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  settlementId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  health_pain?: Prisma.SortOrder
  health_infection?: Prisma.SortOrder
  health_digestion?: Prisma.SortOrder
  health_consciousness?: Prisma.SortOrder
  health_sanity?: Prisma.SortOrder
  capacity_breathing?: Prisma.SortOrder
  capacity_eating?: Prisma.SortOrder
  capacity_hearing?: Prisma.SortOrder
  capacity_moving?: Prisma.SortOrder
  capacity_seeing?: Prisma.SortOrder
  needs_thirst?: Prisma.SortOrder
  needs_hunger?: Prisma.SortOrder
  needs_sleep?: Prisma.SortOrder
  needs_rest?: Prisma.SortOrder
  needs_social?: Prisma.SortOrder
  attr_strength?: Prisma.SortOrder
  attr_constitution?: Prisma.SortOrder
  attr_dexterity?: Prisma.SortOrder
  attr_perception?: Prisma.SortOrder
  attr_intelligence?: Prisma.SortOrder
  attr_wisdom?: Prisma.SortOrder
  skill_digging?: Prisma.SortOrder
  skill_logging?: Prisma.SortOrder
  skill_mining?: Prisma.SortOrder
  skill_foraging?: Prisma.SortOrder
  skill_fishing?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  settlement?: Prisma.SettlementOrderByWithRelationInput
}

export type SettlerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SettlerWhereInput | Prisma.SettlerWhereInput[]
  OR?: Prisma.SettlerWhereInput[]
  NOT?: Prisma.SettlerWhereInput | Prisma.SettlerWhereInput[]
  settlementId?: Prisma.StringFilter<"Settler"> | string
  name?: Prisma.StringFilter<"Settler"> | string
  health_pain?: Prisma.IntFilter<"Settler"> | number
  health_infection?: Prisma.IntFilter<"Settler"> | number
  health_digestion?: Prisma.IntFilter<"Settler"> | number
  health_consciousness?: Prisma.IntFilter<"Settler"> | number
  health_sanity?: Prisma.IntFilter<"Settler"> | number
  capacity_breathing?: Prisma.IntFilter<"Settler"> | number
  capacity_eating?: Prisma.IntFilter<"Settler"> | number
  capacity_hearing?: Prisma.IntFilter<"Settler"> | number
  capacity_moving?: Prisma.IntFilter<"Settler"> | number
  capacity_seeing?: Prisma.IntFilter<"Settler"> | number
  needs_thirst?: Prisma.IntFilter<"Settler"> | number
  needs_hunger?: Prisma.IntFilter<"Settler"> | number
  needs_sleep?: Prisma.IntFilter<"Settler"> | number
  needs_rest?: Prisma.IntFilter<"Settler"> | number
  needs_social?: Prisma.IntFilter<"Settler"> | number
  attr_strength?: Prisma.IntFilter<"Settler"> | number
  attr_constitution?: Prisma.IntFilter<"Settler"> | number
  attr_dexterity?: Prisma.IntFilter<"Settler"> | number
  attr_perception?: Prisma.IntFilter<"Settler"> | number
  attr_intelligence?: Prisma.IntFilter<"Settler"> | number
  attr_wisdom?: Prisma.IntFilter<"Settler"> | number
  skill_digging?: Prisma.IntFilter<"Settler"> | number
  skill_logging?: Prisma.IntFilter<"Settler"> | number
  skill_mining?: Prisma.IntFilter<"Settler"> | number
  skill_foraging?: Prisma.IntFilter<"Settler"> | number
  skill_fishing?: Prisma.IntFilter<"Settler"> | number
  createdAt?: Prisma.DateTimeFilter<"Settler"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Settler"> | Date | string
  settlement?: Prisma.XOR<Prisma.SettlementScalarRelationFilter, Prisma.SettlementWhereInput>
}, "id">

export type SettlerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  settlementId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  health_pain?: Prisma.SortOrder
  health_infection?: Prisma.SortOrder
  health_digestion?: Prisma.SortOrder
  health_consciousness?: Prisma.SortOrder
  health_sanity?: Prisma.SortOrder
  capacity_breathing?: Prisma.SortOrder
  capacity_eating?: Prisma.SortOrder
  capacity_hearing?: Prisma.SortOrder
  capacity_moving?: Prisma.SortOrder
  capacity_seeing?: Prisma.SortOrder
  needs_thirst?: Prisma.SortOrder
  needs_hunger?: Prisma.SortOrder
  needs_sleep?: Prisma.SortOrder
  needs_rest?: Prisma.SortOrder
  needs_social?: Prisma.SortOrder
  attr_strength?: Prisma.SortOrder
  attr_constitution?: Prisma.SortOrder
  attr_dexterity?: Prisma.SortOrder
  attr_perception?: Prisma.SortOrder
  attr_intelligence?: Prisma.SortOrder
  attr_wisdom?: Prisma.SortOrder
  skill_digging?: Prisma.SortOrder
  skill_logging?: Prisma.SortOrder
  skill_mining?: Prisma.SortOrder
  skill_foraging?: Prisma.SortOrder
  skill_fishing?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SettlerCountOrderByAggregateInput
  _avg?: Prisma.SettlerAvgOrderByAggregateInput
  _max?: Prisma.SettlerMaxOrderByAggregateInput
  _min?: Prisma.SettlerMinOrderByAggregateInput
  _sum?: Prisma.SettlerSumOrderByAggregateInput
}

export type SettlerScalarWhereWithAggregatesInput = {
  AND?: Prisma.SettlerScalarWhereWithAggregatesInput | Prisma.SettlerScalarWhereWithAggregatesInput[]
  OR?: Prisma.SettlerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SettlerScalarWhereWithAggregatesInput | Prisma.SettlerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Settler"> | string
  settlementId?: Prisma.StringWithAggregatesFilter<"Settler"> | string
  name?: Prisma.StringWithAggregatesFilter<"Settler"> | string
  health_pain?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  health_infection?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  health_digestion?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  health_consciousness?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  health_sanity?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  capacity_breathing?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  capacity_eating?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  capacity_hearing?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  capacity_moving?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  capacity_seeing?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  needs_thirst?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  needs_hunger?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  needs_sleep?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  needs_rest?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  needs_social?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  attr_strength?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  attr_constitution?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  attr_dexterity?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  attr_perception?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  attr_intelligence?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  attr_wisdom?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  skill_digging?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  skill_logging?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  skill_mining?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  skill_foraging?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  skill_fishing?: Prisma.IntWithAggregatesFilter<"Settler"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Settler"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Settler"> | Date | string
}

export type SettlerCreateInput = {
  id?: string
  name: string
  health_pain?: number
  health_infection?: number
  health_digestion?: number
  health_consciousness?: number
  health_sanity?: number
  capacity_breathing?: number
  capacity_eating?: number
  capacity_hearing?: number
  capacity_moving?: number
  capacity_seeing?: number
  needs_thirst?: number
  needs_hunger?: number
  needs_sleep?: number
  needs_rest?: number
  needs_social?: number
  attr_strength?: number
  attr_constitution?: number
  attr_dexterity?: number
  attr_perception?: number
  attr_intelligence?: number
  attr_wisdom?: number
  skill_digging?: number
  skill_logging?: number
  skill_mining?: number
  skill_foraging?: number
  skill_fishing?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  settlement: Prisma.SettlementCreateNestedOneWithoutSettlersInput
}

export type SettlerUncheckedCreateInput = {
  id?: string
  settlementId: string
  name: string
  health_pain?: number
  health_infection?: number
  health_digestion?: number
  health_consciousness?: number
  health_sanity?: number
  capacity_breathing?: number
  capacity_eating?: number
  capacity_hearing?: number
  capacity_moving?: number
  capacity_seeing?: number
  needs_thirst?: number
  needs_hunger?: number
  needs_sleep?: number
  needs_rest?: number
  needs_social?: number
  attr_strength?: number
  attr_constitution?: number
  attr_dexterity?: number
  attr_perception?: number
  attr_intelligence?: number
  attr_wisdom?: number
  skill_digging?: number
  skill_logging?: number
  skill_mining?: number
  skill_foraging?: number
  skill_fishing?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SettlerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  health_pain?: Prisma.IntFieldUpdateOperationsInput | number
  health_infection?: Prisma.IntFieldUpdateOperationsInput | number
  health_digestion?: Prisma.IntFieldUpdateOperationsInput | number
  health_consciousness?: Prisma.IntFieldUpdateOperationsInput | number
  health_sanity?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_breathing?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_eating?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_hearing?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_moving?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_seeing?: Prisma.IntFieldUpdateOperationsInput | number
  needs_thirst?: Prisma.IntFieldUpdateOperationsInput | number
  needs_hunger?: Prisma.IntFieldUpdateOperationsInput | number
  needs_sleep?: Prisma.IntFieldUpdateOperationsInput | number
  needs_rest?: Prisma.IntFieldUpdateOperationsInput | number
  needs_social?: Prisma.IntFieldUpdateOperationsInput | number
  attr_strength?: Prisma.IntFieldUpdateOperationsInput | number
  attr_constitution?: Prisma.IntFieldUpdateOperationsInput | number
  attr_dexterity?: Prisma.IntFieldUpdateOperationsInput | number
  attr_perception?: Prisma.IntFieldUpdateOperationsInput | number
  attr_intelligence?: Prisma.IntFieldUpdateOperationsInput | number
  attr_wisdom?: Prisma.IntFieldUpdateOperationsInput | number
  skill_digging?: Prisma.IntFieldUpdateOperationsInput | number
  skill_logging?: Prisma.IntFieldUpdateOperationsInput | number
  skill_mining?: Prisma.IntFieldUpdateOperationsInput | number
  skill_foraging?: Prisma.IntFieldUpdateOperationsInput | number
  skill_fishing?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  settlement?: Prisma.SettlementUpdateOneRequiredWithoutSettlersNestedInput
}

export type SettlerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  settlementId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  health_pain?: Prisma.IntFieldUpdateOperationsInput | number
  health_infection?: Prisma.IntFieldUpdateOperationsInput | number
  health_digestion?: Prisma.IntFieldUpdateOperationsInput | number
  health_consciousness?: Prisma.IntFieldUpdateOperationsInput | number
  health_sanity?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_breathing?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_eating?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_hearing?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_moving?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_seeing?: Prisma.IntFieldUpdateOperationsInput | number
  needs_thirst?: Prisma.IntFieldUpdateOperationsInput | number
  needs_hunger?: Prisma.IntFieldUpdateOperationsInput | number
  needs_sleep?: Prisma.IntFieldUpdateOperationsInput | number
  needs_rest?: Prisma.IntFieldUpdateOperationsInput | number
  needs_social?: Prisma.IntFieldUpdateOperationsInput | number
  attr_strength?: Prisma.IntFieldUpdateOperationsInput | number
  attr_constitution?: Prisma.IntFieldUpdateOperationsInput | number
  attr_dexterity?: Prisma.IntFieldUpdateOperationsInput | number
  attr_perception?: Prisma.IntFieldUpdateOperationsInput | number
  attr_intelligence?: Prisma.IntFieldUpdateOperationsInput | number
  attr_wisdom?: Prisma.IntFieldUpdateOperationsInput | number
  skill_digging?: Prisma.IntFieldUpdateOperationsInput | number
  skill_logging?: Prisma.IntFieldUpdateOperationsInput | number
  skill_mining?: Prisma.IntFieldUpdateOperationsInput | number
  skill_foraging?: Prisma.IntFieldUpdateOperationsInput | number
  skill_fishing?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SettlerCreateManyInput = {
  id?: string
  settlementId: string
  name: string
  health_pain?: number
  health_infection?: number
  health_digestion?: number
  health_consciousness?: number
  health_sanity?: number
  capacity_breathing?: number
  capacity_eating?: number
  capacity_hearing?: number
  capacity_moving?: number
  capacity_seeing?: number
  needs_thirst?: number
  needs_hunger?: number
  needs_sleep?: number
  needs_rest?: number
  needs_social?: number
  attr_strength?: number
  attr_constitution?: number
  attr_dexterity?: number
  attr_perception?: number
  attr_intelligence?: number
  attr_wisdom?: number
  skill_digging?: number
  skill_logging?: number
  skill_mining?: number
  skill_foraging?: number
  skill_fishing?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SettlerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  health_pain?: Prisma.IntFieldUpdateOperationsInput | number
  health_infection?: Prisma.IntFieldUpdateOperationsInput | number
  health_digestion?: Prisma.IntFieldUpdateOperationsInput | number
  health_consciousness?: Prisma.IntFieldUpdateOperationsInput | number
  health_sanity?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_breathing?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_eating?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_hearing?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_moving?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_seeing?: Prisma.IntFieldUpdateOperationsInput | number
  needs_thirst?: Prisma.IntFieldUpdateOperationsInput | number
  needs_hunger?: Prisma.IntFieldUpdateOperationsInput | number
  needs_sleep?: Prisma.IntFieldUpdateOperationsInput | number
  needs_rest?: Prisma.IntFieldUpdateOperationsInput | number
  needs_social?: Prisma.IntFieldUpdateOperationsInput | number
  attr_strength?: Prisma.IntFieldUpdateOperationsInput | number
  attr_constitution?: Prisma.IntFieldUpdateOperationsInput | number
  attr_dexterity?: Prisma.IntFieldUpdateOperationsInput | number
  attr_perception?: Prisma.IntFieldUpdateOperationsInput | number
  attr_intelligence?: Prisma.IntFieldUpdateOperationsInput | number
  attr_wisdom?: Prisma.IntFieldUpdateOperationsInput | number
  skill_digging?: Prisma.IntFieldUpdateOperationsInput | number
  skill_logging?: Prisma.IntFieldUpdateOperationsInput | number
  skill_mining?: Prisma.IntFieldUpdateOperationsInput | number
  skill_foraging?: Prisma.IntFieldUpdateOperationsInput | number
  skill_fishing?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SettlerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  settlementId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  health_pain?: Prisma.IntFieldUpdateOperationsInput | number
  health_infection?: Prisma.IntFieldUpdateOperationsInput | number
  health_digestion?: Prisma.IntFieldUpdateOperationsInput | number
  health_consciousness?: Prisma.IntFieldUpdateOperationsInput | number
  health_sanity?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_breathing?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_eating?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_hearing?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_moving?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_seeing?: Prisma.IntFieldUpdateOperationsInput | number
  needs_thirst?: Prisma.IntFieldUpdateOperationsInput | number
  needs_hunger?: Prisma.IntFieldUpdateOperationsInput | number
  needs_sleep?: Prisma.IntFieldUpdateOperationsInput | number
  needs_rest?: Prisma.IntFieldUpdateOperationsInput | number
  needs_social?: Prisma.IntFieldUpdateOperationsInput | number
  attr_strength?: Prisma.IntFieldUpdateOperationsInput | number
  attr_constitution?: Prisma.IntFieldUpdateOperationsInput | number
  attr_dexterity?: Prisma.IntFieldUpdateOperationsInput | number
  attr_perception?: Prisma.IntFieldUpdateOperationsInput | number
  attr_intelligence?: Prisma.IntFieldUpdateOperationsInput | number
  attr_wisdom?: Prisma.IntFieldUpdateOperationsInput | number
  skill_digging?: Prisma.IntFieldUpdateOperationsInput | number
  skill_logging?: Prisma.IntFieldUpdateOperationsInput | number
  skill_mining?: Prisma.IntFieldUpdateOperationsInput | number
  skill_foraging?: Prisma.IntFieldUpdateOperationsInput | number
  skill_fishing?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SettlerListRelationFilter = {
  every?: Prisma.SettlerWhereInput
  some?: Prisma.SettlerWhereInput
  none?: Prisma.SettlerWhereInput
}

export type SettlerOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SettlerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  settlementId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  health_pain?: Prisma.SortOrder
  health_infection?: Prisma.SortOrder
  health_digestion?: Prisma.SortOrder
  health_consciousness?: Prisma.SortOrder
  health_sanity?: Prisma.SortOrder
  capacity_breathing?: Prisma.SortOrder
  capacity_eating?: Prisma.SortOrder
  capacity_hearing?: Prisma.SortOrder
  capacity_moving?: Prisma.SortOrder
  capacity_seeing?: Prisma.SortOrder
  needs_thirst?: Prisma.SortOrder
  needs_hunger?: Prisma.SortOrder
  needs_sleep?: Prisma.SortOrder
  needs_rest?: Prisma.SortOrder
  needs_social?: Prisma.SortOrder
  attr_strength?: Prisma.SortOrder
  attr_constitution?: Prisma.SortOrder
  attr_dexterity?: Prisma.SortOrder
  attr_perception?: Prisma.SortOrder
  attr_intelligence?: Prisma.SortOrder
  attr_wisdom?: Prisma.SortOrder
  skill_digging?: Prisma.SortOrder
  skill_logging?: Prisma.SortOrder
  skill_mining?: Prisma.SortOrder
  skill_foraging?: Prisma.SortOrder
  skill_fishing?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SettlerAvgOrderByAggregateInput = {
  health_pain?: Prisma.SortOrder
  health_infection?: Prisma.SortOrder
  health_digestion?: Prisma.SortOrder
  health_consciousness?: Prisma.SortOrder
  health_sanity?: Prisma.SortOrder
  capacity_breathing?: Prisma.SortOrder
  capacity_eating?: Prisma.SortOrder
  capacity_hearing?: Prisma.SortOrder
  capacity_moving?: Prisma.SortOrder
  capacity_seeing?: Prisma.SortOrder
  needs_thirst?: Prisma.SortOrder
  needs_hunger?: Prisma.SortOrder
  needs_sleep?: Prisma.SortOrder
  needs_rest?: Prisma.SortOrder
  needs_social?: Prisma.SortOrder
  attr_strength?: Prisma.SortOrder
  attr_constitution?: Prisma.SortOrder
  attr_dexterity?: Prisma.SortOrder
  attr_perception?: Prisma.SortOrder
  attr_intelligence?: Prisma.SortOrder
  attr_wisdom?: Prisma.SortOrder
  skill_digging?: Prisma.SortOrder
  skill_logging?: Prisma.SortOrder
  skill_mining?: Prisma.SortOrder
  skill_foraging?: Prisma.SortOrder
  skill_fishing?: Prisma.SortOrder
}

export type SettlerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  settlementId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  health_pain?: Prisma.SortOrder
  health_infection?: Prisma.SortOrder
  health_digestion?: Prisma.SortOrder
  health_consciousness?: Prisma.SortOrder
  health_sanity?: Prisma.SortOrder
  capacity_breathing?: Prisma.SortOrder
  capacity_eating?: Prisma.SortOrder
  capacity_hearing?: Prisma.SortOrder
  capacity_moving?: Prisma.SortOrder
  capacity_seeing?: Prisma.SortOrder
  needs_thirst?: Prisma.SortOrder
  needs_hunger?: Prisma.SortOrder
  needs_sleep?: Prisma.SortOrder
  needs_rest?: Prisma.SortOrder
  needs_social?: Prisma.SortOrder
  attr_strength?: Prisma.SortOrder
  attr_constitution?: Prisma.SortOrder
  attr_dexterity?: Prisma.SortOrder
  attr_perception?: Prisma.SortOrder
  attr_intelligence?: Prisma.SortOrder
  attr_wisdom?: Prisma.SortOrder
  skill_digging?: Prisma.SortOrder
  skill_logging?: Prisma.SortOrder
  skill_mining?: Prisma.SortOrder
  skill_foraging?: Prisma.SortOrder
  skill_fishing?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SettlerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  settlementId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  health_pain?: Prisma.SortOrder
  health_infection?: Prisma.SortOrder
  health_digestion?: Prisma.SortOrder
  health_consciousness?: Prisma.SortOrder
  health_sanity?: Prisma.SortOrder
  capacity_breathing?: Prisma.SortOrder
  capacity_eating?: Prisma.SortOrder
  capacity_hearing?: Prisma.SortOrder
  capacity_moving?: Prisma.SortOrder
  capacity_seeing?: Prisma.SortOrder
  needs_thirst?: Prisma.SortOrder
  needs_hunger?: Prisma.SortOrder
  needs_sleep?: Prisma.SortOrder
  needs_rest?: Prisma.SortOrder
  needs_social?: Prisma.SortOrder
  attr_strength?: Prisma.SortOrder
  attr_constitution?: Prisma.SortOrder
  attr_dexterity?: Prisma.SortOrder
  attr_perception?: Prisma.SortOrder
  attr_intelligence?: Prisma.SortOrder
  attr_wisdom?: Prisma.SortOrder
  skill_digging?: Prisma.SortOrder
  skill_logging?: Prisma.SortOrder
  skill_mining?: Prisma.SortOrder
  skill_foraging?: Prisma.SortOrder
  skill_fishing?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SettlerSumOrderByAggregateInput = {
  health_pain?: Prisma.SortOrder
  health_infection?: Prisma.SortOrder
  health_digestion?: Prisma.SortOrder
  health_consciousness?: Prisma.SortOrder
  health_sanity?: Prisma.SortOrder
  capacity_breathing?: Prisma.SortOrder
  capacity_eating?: Prisma.SortOrder
  capacity_hearing?: Prisma.SortOrder
  capacity_moving?: Prisma.SortOrder
  capacity_seeing?: Prisma.SortOrder
  needs_thirst?: Prisma.SortOrder
  needs_hunger?: Prisma.SortOrder
  needs_sleep?: Prisma.SortOrder
  needs_rest?: Prisma.SortOrder
  needs_social?: Prisma.SortOrder
  attr_strength?: Prisma.SortOrder
  attr_constitution?: Prisma.SortOrder
  attr_dexterity?: Prisma.SortOrder
  attr_perception?: Prisma.SortOrder
  attr_intelligence?: Prisma.SortOrder
  attr_wisdom?: Prisma.SortOrder
  skill_digging?: Prisma.SortOrder
  skill_logging?: Prisma.SortOrder
  skill_mining?: Prisma.SortOrder
  skill_foraging?: Prisma.SortOrder
  skill_fishing?: Prisma.SortOrder
}

export type SettlerCreateNestedManyWithoutSettlementInput = {
  create?: Prisma.XOR<Prisma.SettlerCreateWithoutSettlementInput, Prisma.SettlerUncheckedCreateWithoutSettlementInput> | Prisma.SettlerCreateWithoutSettlementInput[] | Prisma.SettlerUncheckedCreateWithoutSettlementInput[]
  connectOrCreate?: Prisma.SettlerCreateOrConnectWithoutSettlementInput | Prisma.SettlerCreateOrConnectWithoutSettlementInput[]
  createMany?: Prisma.SettlerCreateManySettlementInputEnvelope
  connect?: Prisma.SettlerWhereUniqueInput | Prisma.SettlerWhereUniqueInput[]
}

export type SettlerUncheckedCreateNestedManyWithoutSettlementInput = {
  create?: Prisma.XOR<Prisma.SettlerCreateWithoutSettlementInput, Prisma.SettlerUncheckedCreateWithoutSettlementInput> | Prisma.SettlerCreateWithoutSettlementInput[] | Prisma.SettlerUncheckedCreateWithoutSettlementInput[]
  connectOrCreate?: Prisma.SettlerCreateOrConnectWithoutSettlementInput | Prisma.SettlerCreateOrConnectWithoutSettlementInput[]
  createMany?: Prisma.SettlerCreateManySettlementInputEnvelope
  connect?: Prisma.SettlerWhereUniqueInput | Prisma.SettlerWhereUniqueInput[]
}

export type SettlerUpdateManyWithoutSettlementNestedInput = {
  create?: Prisma.XOR<Prisma.SettlerCreateWithoutSettlementInput, Prisma.SettlerUncheckedCreateWithoutSettlementInput> | Prisma.SettlerCreateWithoutSettlementInput[] | Prisma.SettlerUncheckedCreateWithoutSettlementInput[]
  connectOrCreate?: Prisma.SettlerCreateOrConnectWithoutSettlementInput | Prisma.SettlerCreateOrConnectWithoutSettlementInput[]
  upsert?: Prisma.SettlerUpsertWithWhereUniqueWithoutSettlementInput | Prisma.SettlerUpsertWithWhereUniqueWithoutSettlementInput[]
  createMany?: Prisma.SettlerCreateManySettlementInputEnvelope
  set?: Prisma.SettlerWhereUniqueInput | Prisma.SettlerWhereUniqueInput[]
  disconnect?: Prisma.SettlerWhereUniqueInput | Prisma.SettlerWhereUniqueInput[]
  delete?: Prisma.SettlerWhereUniqueInput | Prisma.SettlerWhereUniqueInput[]
  connect?: Prisma.SettlerWhereUniqueInput | Prisma.SettlerWhereUniqueInput[]
  update?: Prisma.SettlerUpdateWithWhereUniqueWithoutSettlementInput | Prisma.SettlerUpdateWithWhereUniqueWithoutSettlementInput[]
  updateMany?: Prisma.SettlerUpdateManyWithWhereWithoutSettlementInput | Prisma.SettlerUpdateManyWithWhereWithoutSettlementInput[]
  deleteMany?: Prisma.SettlerScalarWhereInput | Prisma.SettlerScalarWhereInput[]
}

export type SettlerUncheckedUpdateManyWithoutSettlementNestedInput = {
  create?: Prisma.XOR<Prisma.SettlerCreateWithoutSettlementInput, Prisma.SettlerUncheckedCreateWithoutSettlementInput> | Prisma.SettlerCreateWithoutSettlementInput[] | Prisma.SettlerUncheckedCreateWithoutSettlementInput[]
  connectOrCreate?: Prisma.SettlerCreateOrConnectWithoutSettlementInput | Prisma.SettlerCreateOrConnectWithoutSettlementInput[]
  upsert?: Prisma.SettlerUpsertWithWhereUniqueWithoutSettlementInput | Prisma.SettlerUpsertWithWhereUniqueWithoutSettlementInput[]
  createMany?: Prisma.SettlerCreateManySettlementInputEnvelope
  set?: Prisma.SettlerWhereUniqueInput | Prisma.SettlerWhereUniqueInput[]
  disconnect?: Prisma.SettlerWhereUniqueInput | Prisma.SettlerWhereUniqueInput[]
  delete?: Prisma.SettlerWhereUniqueInput | Prisma.SettlerWhereUniqueInput[]
  connect?: Prisma.SettlerWhereUniqueInput | Prisma.SettlerWhereUniqueInput[]
  update?: Prisma.SettlerUpdateWithWhereUniqueWithoutSettlementInput | Prisma.SettlerUpdateWithWhereUniqueWithoutSettlementInput[]
  updateMany?: Prisma.SettlerUpdateManyWithWhereWithoutSettlementInput | Prisma.SettlerUpdateManyWithWhereWithoutSettlementInput[]
  deleteMany?: Prisma.SettlerScalarWhereInput | Prisma.SettlerScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type SettlerCreateWithoutSettlementInput = {
  id?: string
  name: string
  health_pain?: number
  health_infection?: number
  health_digestion?: number
  health_consciousness?: number
  health_sanity?: number
  capacity_breathing?: number
  capacity_eating?: number
  capacity_hearing?: number
  capacity_moving?: number
  capacity_seeing?: number
  needs_thirst?: number
  needs_hunger?: number
  needs_sleep?: number
  needs_rest?: number
  needs_social?: number
  attr_strength?: number
  attr_constitution?: number
  attr_dexterity?: number
  attr_perception?: number
  attr_intelligence?: number
  attr_wisdom?: number
  skill_digging?: number
  skill_logging?: number
  skill_mining?: number
  skill_foraging?: number
  skill_fishing?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SettlerUncheckedCreateWithoutSettlementInput = {
  id?: string
  name: string
  health_pain?: number
  health_infection?: number
  health_digestion?: number
  health_consciousness?: number
  health_sanity?: number
  capacity_breathing?: number
  capacity_eating?: number
  capacity_hearing?: number
  capacity_moving?: number
  capacity_seeing?: number
  needs_thirst?: number
  needs_hunger?: number
  needs_sleep?: number
  needs_rest?: number
  needs_social?: number
  attr_strength?: number
  attr_constitution?: number
  attr_dexterity?: number
  attr_perception?: number
  attr_intelligence?: number
  attr_wisdom?: number
  skill_digging?: number
  skill_logging?: number
  skill_mining?: number
  skill_foraging?: number
  skill_fishing?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SettlerCreateOrConnectWithoutSettlementInput = {
  where: Prisma.SettlerWhereUniqueInput
  create: Prisma.XOR<Prisma.SettlerCreateWithoutSettlementInput, Prisma.SettlerUncheckedCreateWithoutSettlementInput>
}

export type SettlerCreateManySettlementInputEnvelope = {
  data: Prisma.SettlerCreateManySettlementInput | Prisma.SettlerCreateManySettlementInput[]
  skipDuplicates?: boolean
}

export type SettlerUpsertWithWhereUniqueWithoutSettlementInput = {
  where: Prisma.SettlerWhereUniqueInput
  update: Prisma.XOR<Prisma.SettlerUpdateWithoutSettlementInput, Prisma.SettlerUncheckedUpdateWithoutSettlementInput>
  create: Prisma.XOR<Prisma.SettlerCreateWithoutSettlementInput, Prisma.SettlerUncheckedCreateWithoutSettlementInput>
}

export type SettlerUpdateWithWhereUniqueWithoutSettlementInput = {
  where: Prisma.SettlerWhereUniqueInput
  data: Prisma.XOR<Prisma.SettlerUpdateWithoutSettlementInput, Prisma.SettlerUncheckedUpdateWithoutSettlementInput>
}

export type SettlerUpdateManyWithWhereWithoutSettlementInput = {
  where: Prisma.SettlerScalarWhereInput
  data: Prisma.XOR<Prisma.SettlerUpdateManyMutationInput, Prisma.SettlerUncheckedUpdateManyWithoutSettlementInput>
}

export type SettlerScalarWhereInput = {
  AND?: Prisma.SettlerScalarWhereInput | Prisma.SettlerScalarWhereInput[]
  OR?: Prisma.SettlerScalarWhereInput[]
  NOT?: Prisma.SettlerScalarWhereInput | Prisma.SettlerScalarWhereInput[]
  id?: Prisma.StringFilter<"Settler"> | string
  settlementId?: Prisma.StringFilter<"Settler"> | string
  name?: Prisma.StringFilter<"Settler"> | string
  health_pain?: Prisma.IntFilter<"Settler"> | number
  health_infection?: Prisma.IntFilter<"Settler"> | number
  health_digestion?: Prisma.IntFilter<"Settler"> | number
  health_consciousness?: Prisma.IntFilter<"Settler"> | number
  health_sanity?: Prisma.IntFilter<"Settler"> | number
  capacity_breathing?: Prisma.IntFilter<"Settler"> | number
  capacity_eating?: Prisma.IntFilter<"Settler"> | number
  capacity_hearing?: Prisma.IntFilter<"Settler"> | number
  capacity_moving?: Prisma.IntFilter<"Settler"> | number
  capacity_seeing?: Prisma.IntFilter<"Settler"> | number
  needs_thirst?: Prisma.IntFilter<"Settler"> | number
  needs_hunger?: Prisma.IntFilter<"Settler"> | number
  needs_sleep?: Prisma.IntFilter<"Settler"> | number
  needs_rest?: Prisma.IntFilter<"Settler"> | number
  needs_social?: Prisma.IntFilter<"Settler"> | number
  attr_strength?: Prisma.IntFilter<"Settler"> | number
  attr_constitution?: Prisma.IntFilter<"Settler"> | number
  attr_dexterity?: Prisma.IntFilter<"Settler"> | number
  attr_perception?: Prisma.IntFilter<"Settler"> | number
  attr_intelligence?: Prisma.IntFilter<"Settler"> | number
  attr_wisdom?: Prisma.IntFilter<"Settler"> | number
  skill_digging?: Prisma.IntFilter<"Settler"> | number
  skill_logging?: Prisma.IntFilter<"Settler"> | number
  skill_mining?: Prisma.IntFilter<"Settler"> | number
  skill_foraging?: Prisma.IntFilter<"Settler"> | number
  skill_fishing?: Prisma.IntFilter<"Settler"> | number
  createdAt?: Prisma.DateTimeFilter<"Settler"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Settler"> | Date | string
}

export type SettlerCreateManySettlementInput = {
  id?: string
  name: string
  health_pain?: number
  health_infection?: number
  health_digestion?: number
  health_consciousness?: number
  health_sanity?: number
  capacity_breathing?: number
  capacity_eating?: number
  capacity_hearing?: number
  capacity_moving?: number
  capacity_seeing?: number
  needs_thirst?: number
  needs_hunger?: number
  needs_sleep?: number
  needs_rest?: number
  needs_social?: number
  attr_strength?: number
  attr_constitution?: number
  attr_dexterity?: number
  attr_perception?: number
  attr_intelligence?: number
  attr_wisdom?: number
  skill_digging?: number
  skill_logging?: number
  skill_mining?: number
  skill_foraging?: number
  skill_fishing?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SettlerUpdateWithoutSettlementInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  health_pain?: Prisma.IntFieldUpdateOperationsInput | number
  health_infection?: Prisma.IntFieldUpdateOperationsInput | number
  health_digestion?: Prisma.IntFieldUpdateOperationsInput | number
  health_consciousness?: Prisma.IntFieldUpdateOperationsInput | number
  health_sanity?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_breathing?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_eating?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_hearing?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_moving?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_seeing?: Prisma.IntFieldUpdateOperationsInput | number
  needs_thirst?: Prisma.IntFieldUpdateOperationsInput | number
  needs_hunger?: Prisma.IntFieldUpdateOperationsInput | number
  needs_sleep?: Prisma.IntFieldUpdateOperationsInput | number
  needs_rest?: Prisma.IntFieldUpdateOperationsInput | number
  needs_social?: Prisma.IntFieldUpdateOperationsInput | number
  attr_strength?: Prisma.IntFieldUpdateOperationsInput | number
  attr_constitution?: Prisma.IntFieldUpdateOperationsInput | number
  attr_dexterity?: Prisma.IntFieldUpdateOperationsInput | number
  attr_perception?: Prisma.IntFieldUpdateOperationsInput | number
  attr_intelligence?: Prisma.IntFieldUpdateOperationsInput | number
  attr_wisdom?: Prisma.IntFieldUpdateOperationsInput | number
  skill_digging?: Prisma.IntFieldUpdateOperationsInput | number
  skill_logging?: Prisma.IntFieldUpdateOperationsInput | number
  skill_mining?: Prisma.IntFieldUpdateOperationsInput | number
  skill_foraging?: Prisma.IntFieldUpdateOperationsInput | number
  skill_fishing?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SettlerUncheckedUpdateWithoutSettlementInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  health_pain?: Prisma.IntFieldUpdateOperationsInput | number
  health_infection?: Prisma.IntFieldUpdateOperationsInput | number
  health_digestion?: Prisma.IntFieldUpdateOperationsInput | number
  health_consciousness?: Prisma.IntFieldUpdateOperationsInput | number
  health_sanity?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_breathing?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_eating?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_hearing?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_moving?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_seeing?: Prisma.IntFieldUpdateOperationsInput | number
  needs_thirst?: Prisma.IntFieldUpdateOperationsInput | number
  needs_hunger?: Prisma.IntFieldUpdateOperationsInput | number
  needs_sleep?: Prisma.IntFieldUpdateOperationsInput | number
  needs_rest?: Prisma.IntFieldUpdateOperationsInput | number
  needs_social?: Prisma.IntFieldUpdateOperationsInput | number
  attr_strength?: Prisma.IntFieldUpdateOperationsInput | number
  attr_constitution?: Prisma.IntFieldUpdateOperationsInput | number
  attr_dexterity?: Prisma.IntFieldUpdateOperationsInput | number
  attr_perception?: Prisma.IntFieldUpdateOperationsInput | number
  attr_intelligence?: Prisma.IntFieldUpdateOperationsInput | number
  attr_wisdom?: Prisma.IntFieldUpdateOperationsInput | number
  skill_digging?: Prisma.IntFieldUpdateOperationsInput | number
  skill_logging?: Prisma.IntFieldUpdateOperationsInput | number
  skill_mining?: Prisma.IntFieldUpdateOperationsInput | number
  skill_foraging?: Prisma.IntFieldUpdateOperationsInput | number
  skill_fishing?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SettlerUncheckedUpdateManyWithoutSettlementInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  health_pain?: Prisma.IntFieldUpdateOperationsInput | number
  health_infection?: Prisma.IntFieldUpdateOperationsInput | number
  health_digestion?: Prisma.IntFieldUpdateOperationsInput | number
  health_consciousness?: Prisma.IntFieldUpdateOperationsInput | number
  health_sanity?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_breathing?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_eating?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_hearing?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_moving?: Prisma.IntFieldUpdateOperationsInput | number
  capacity_seeing?: Prisma.IntFieldUpdateOperationsInput | number
  needs_thirst?: Prisma.IntFieldUpdateOperationsInput | number
  needs_hunger?: Prisma.IntFieldUpdateOperationsInput | number
  needs_sleep?: Prisma.IntFieldUpdateOperationsInput | number
  needs_rest?: Prisma.IntFieldUpdateOperationsInput | number
  needs_social?: Prisma.IntFieldUpdateOperationsInput | number
  attr_strength?: Prisma.IntFieldUpdateOperationsInput | number
  attr_constitution?: Prisma.IntFieldUpdateOperationsInput | number
  attr_dexterity?: Prisma.IntFieldUpdateOperationsInput | number
  attr_perception?: Prisma.IntFieldUpdateOperationsInput | number
  attr_intelligence?: Prisma.IntFieldUpdateOperationsInput | number
  attr_wisdom?: Prisma.IntFieldUpdateOperationsInput | number
  skill_digging?: Prisma.IntFieldUpdateOperationsInput | number
  skill_logging?: Prisma.IntFieldUpdateOperationsInput | number
  skill_mining?: Prisma.IntFieldUpdateOperationsInput | number
  skill_foraging?: Prisma.IntFieldUpdateOperationsInput | number
  skill_fishing?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type SettlerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  settlementId?: boolean
  name?: boolean
  health_pain?: boolean
  health_infection?: boolean
  health_digestion?: boolean
  health_consciousness?: boolean
  health_sanity?: boolean
  capacity_breathing?: boolean
  capacity_eating?: boolean
  capacity_hearing?: boolean
  capacity_moving?: boolean
  capacity_seeing?: boolean
  needs_thirst?: boolean
  needs_hunger?: boolean
  needs_sleep?: boolean
  needs_rest?: boolean
  needs_social?: boolean
  attr_strength?: boolean
  attr_constitution?: boolean
  attr_dexterity?: boolean
  attr_perception?: boolean
  attr_intelligence?: boolean
  attr_wisdom?: boolean
  skill_digging?: boolean
  skill_logging?: boolean
  skill_mining?: boolean
  skill_foraging?: boolean
  skill_fishing?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  settlement?: boolean | Prisma.SettlementDefaultArgs<ExtArgs>
}, ExtArgs["result"]["settler"]>

export type SettlerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  settlementId?: boolean
  name?: boolean
  health_pain?: boolean
  health_infection?: boolean
  health_digestion?: boolean
  health_consciousness?: boolean
  health_sanity?: boolean
  capacity_breathing?: boolean
  capacity_eating?: boolean
  capacity_hearing?: boolean
  capacity_moving?: boolean
  capacity_seeing?: boolean
  needs_thirst?: boolean
  needs_hunger?: boolean
  needs_sleep?: boolean
  needs_rest?: boolean
  needs_social?: boolean
  attr_strength?: boolean
  attr_constitution?: boolean
  attr_dexterity?: boolean
  attr_perception?: boolean
  attr_intelligence?: boolean
  attr_wisdom?: boolean
  skill_digging?: boolean
  skill_logging?: boolean
  skill_mining?: boolean
  skill_foraging?: boolean
  skill_fishing?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  settlement?: boolean | Prisma.SettlementDefaultArgs<ExtArgs>
}, ExtArgs["result"]["settler"]>

export type SettlerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  settlementId?: boolean
  name?: boolean
  health_pain?: boolean
  health_infection?: boolean
  health_digestion?: boolean
  health_consciousness?: boolean
  health_sanity?: boolean
  capacity_breathing?: boolean
  capacity_eating?: boolean
  capacity_hearing?: boolean
  capacity_moving?: boolean
  capacity_seeing?: boolean
  needs_thirst?: boolean
  needs_hunger?: boolean
  needs_sleep?: boolean
  needs_rest?: boolean
  needs_social?: boolean
  attr_strength?: boolean
  attr_constitution?: boolean
  attr_dexterity?: boolean
  attr_perception?: boolean
  attr_intelligence?: boolean
  attr_wisdom?: boolean
  skill_digging?: boolean
  skill_logging?: boolean
  skill_mining?: boolean
  skill_foraging?: boolean
  skill_fishing?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  settlement?: boolean | Prisma.SettlementDefaultArgs<ExtArgs>
}, ExtArgs["result"]["settler"]>

export type SettlerSelectScalar = {
  id?: boolean
  settlementId?: boolean
  name?: boolean
  health_pain?: boolean
  health_infection?: boolean
  health_digestion?: boolean
  health_consciousness?: boolean
  health_sanity?: boolean
  capacity_breathing?: boolean
  capacity_eating?: boolean
  capacity_hearing?: boolean
  capacity_moving?: boolean
  capacity_seeing?: boolean
  needs_thirst?: boolean
  needs_hunger?: boolean
  needs_sleep?: boolean
  needs_rest?: boolean
  needs_social?: boolean
  attr_strength?: boolean
  attr_constitution?: boolean
  attr_dexterity?: boolean
  attr_perception?: boolean
  attr_intelligence?: boolean
  attr_wisdom?: boolean
  skill_digging?: boolean
  skill_logging?: boolean
  skill_mining?: boolean
  skill_foraging?: boolean
  skill_fishing?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type SettlerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "settlementId" | "name" | "health_pain" | "health_infection" | "health_digestion" | "health_consciousness" | "health_sanity" | "capacity_breathing" | "capacity_eating" | "capacity_hearing" | "capacity_moving" | "capacity_seeing" | "needs_thirst" | "needs_hunger" | "needs_sleep" | "needs_rest" | "needs_social" | "attr_strength" | "attr_constitution" | "attr_dexterity" | "attr_perception" | "attr_intelligence" | "attr_wisdom" | "skill_digging" | "skill_logging" | "skill_mining" | "skill_foraging" | "skill_fishing" | "createdAt" | "updatedAt", ExtArgs["result"]["settler"]>
export type SettlerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  settlement?: boolean | Prisma.SettlementDefaultArgs<ExtArgs>
}
export type SettlerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  settlement?: boolean | Prisma.SettlementDefaultArgs<ExtArgs>
}
export type SettlerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  settlement?: boolean | Prisma.SettlementDefaultArgs<ExtArgs>
}

export type $SettlerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Settler"
  objects: {
    settlement: Prisma.$SettlementPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    settlementId: string
    name: string
    health_pain: number
    health_infection: number
    health_digestion: number
    health_consciousness: number
    health_sanity: number
    capacity_breathing: number
    capacity_eating: number
    capacity_hearing: number
    capacity_moving: number
    capacity_seeing: number
    needs_thirst: number
    needs_hunger: number
    needs_sleep: number
    needs_rest: number
    needs_social: number
    attr_strength: number
    attr_constitution: number
    attr_dexterity: number
    attr_perception: number
    attr_intelligence: number
    attr_wisdom: number
    skill_digging: number
    skill_logging: number
    skill_mining: number
    skill_foraging: number
    skill_fishing: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["settler"]>
  composites: {}
}

export type SettlerGetPayload<S extends boolean | null | undefined | SettlerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SettlerPayload, S>

export type SettlerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SettlerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SettlerCountAggregateInputType | true
  }

export interface SettlerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Settler'], meta: { name: 'Settler' } }
  /**
   * Find zero or one Settler that matches the filter.
   * @param {SettlerFindUniqueArgs} args - Arguments to find a Settler
   * @example
   * // Get one Settler
   * const settler = await prisma.settler.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SettlerFindUniqueArgs>(args: Prisma.SelectSubset<T, SettlerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SettlerClient<runtime.Types.Result.GetResult<Prisma.$SettlerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Settler that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SettlerFindUniqueOrThrowArgs} args - Arguments to find a Settler
   * @example
   * // Get one Settler
   * const settler = await prisma.settler.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SettlerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SettlerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SettlerClient<runtime.Types.Result.GetResult<Prisma.$SettlerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Settler that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SettlerFindFirstArgs} args - Arguments to find a Settler
   * @example
   * // Get one Settler
   * const settler = await prisma.settler.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SettlerFindFirstArgs>(args?: Prisma.SelectSubset<T, SettlerFindFirstArgs<ExtArgs>>): Prisma.Prisma__SettlerClient<runtime.Types.Result.GetResult<Prisma.$SettlerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Settler that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SettlerFindFirstOrThrowArgs} args - Arguments to find a Settler
   * @example
   * // Get one Settler
   * const settler = await prisma.settler.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SettlerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SettlerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SettlerClient<runtime.Types.Result.GetResult<Prisma.$SettlerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Settlers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SettlerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Settlers
   * const settlers = await prisma.settler.findMany()
   * 
   * // Get first 10 Settlers
   * const settlers = await prisma.settler.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const settlerWithIdOnly = await prisma.settler.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SettlerFindManyArgs>(args?: Prisma.SelectSubset<T, SettlerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SettlerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Settler.
   * @param {SettlerCreateArgs} args - Arguments to create a Settler.
   * @example
   * // Create one Settler
   * const Settler = await prisma.settler.create({
   *   data: {
   *     // ... data to create a Settler
   *   }
   * })
   * 
   */
  create<T extends SettlerCreateArgs>(args: Prisma.SelectSubset<T, SettlerCreateArgs<ExtArgs>>): Prisma.Prisma__SettlerClient<runtime.Types.Result.GetResult<Prisma.$SettlerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Settlers.
   * @param {SettlerCreateManyArgs} args - Arguments to create many Settlers.
   * @example
   * // Create many Settlers
   * const settler = await prisma.settler.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SettlerCreateManyArgs>(args?: Prisma.SelectSubset<T, SettlerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Settlers and returns the data saved in the database.
   * @param {SettlerCreateManyAndReturnArgs} args - Arguments to create many Settlers.
   * @example
   * // Create many Settlers
   * const settler = await prisma.settler.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Settlers and only return the `id`
   * const settlerWithIdOnly = await prisma.settler.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SettlerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SettlerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SettlerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Settler.
   * @param {SettlerDeleteArgs} args - Arguments to delete one Settler.
   * @example
   * // Delete one Settler
   * const Settler = await prisma.settler.delete({
   *   where: {
   *     // ... filter to delete one Settler
   *   }
   * })
   * 
   */
  delete<T extends SettlerDeleteArgs>(args: Prisma.SelectSubset<T, SettlerDeleteArgs<ExtArgs>>): Prisma.Prisma__SettlerClient<runtime.Types.Result.GetResult<Prisma.$SettlerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Settler.
   * @param {SettlerUpdateArgs} args - Arguments to update one Settler.
   * @example
   * // Update one Settler
   * const settler = await prisma.settler.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SettlerUpdateArgs>(args: Prisma.SelectSubset<T, SettlerUpdateArgs<ExtArgs>>): Prisma.Prisma__SettlerClient<runtime.Types.Result.GetResult<Prisma.$SettlerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Settlers.
   * @param {SettlerDeleteManyArgs} args - Arguments to filter Settlers to delete.
   * @example
   * // Delete a few Settlers
   * const { count } = await prisma.settler.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SettlerDeleteManyArgs>(args?: Prisma.SelectSubset<T, SettlerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Settlers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SettlerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Settlers
   * const settler = await prisma.settler.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SettlerUpdateManyArgs>(args: Prisma.SelectSubset<T, SettlerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Settlers and returns the data updated in the database.
   * @param {SettlerUpdateManyAndReturnArgs} args - Arguments to update many Settlers.
   * @example
   * // Update many Settlers
   * const settler = await prisma.settler.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Settlers and only return the `id`
   * const settlerWithIdOnly = await prisma.settler.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SettlerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SettlerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SettlerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Settler.
   * @param {SettlerUpsertArgs} args - Arguments to update or create a Settler.
   * @example
   * // Update or create a Settler
   * const settler = await prisma.settler.upsert({
   *   create: {
   *     // ... data to create a Settler
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Settler we want to update
   *   }
   * })
   */
  upsert<T extends SettlerUpsertArgs>(args: Prisma.SelectSubset<T, SettlerUpsertArgs<ExtArgs>>): Prisma.Prisma__SettlerClient<runtime.Types.Result.GetResult<Prisma.$SettlerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Settlers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SettlerCountArgs} args - Arguments to filter Settlers to count.
   * @example
   * // Count the number of Settlers
   * const count = await prisma.settler.count({
   *   where: {
   *     // ... the filter for the Settlers we want to count
   *   }
   * })
  **/
  count<T extends SettlerCountArgs>(
    args?: Prisma.Subset<T, SettlerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SettlerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Settler.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SettlerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SettlerAggregateArgs>(args: Prisma.Subset<T, SettlerAggregateArgs>): Prisma.PrismaPromise<GetSettlerAggregateType<T>>

  /**
   * Group by Settler.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SettlerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SettlerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SettlerGroupByArgs['orderBy'] }
      : { orderBy?: SettlerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SettlerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSettlerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Settler model
 */
readonly fields: SettlerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Settler.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SettlerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  settlement<T extends Prisma.SettlementDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SettlementDefaultArgs<ExtArgs>>): Prisma.Prisma__SettlementClient<runtime.Types.Result.GetResult<Prisma.$SettlementPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Settler model
 */
export interface SettlerFieldRefs {
  readonly id: Prisma.FieldRef<"Settler", 'String'>
  readonly settlementId: Prisma.FieldRef<"Settler", 'String'>
  readonly name: Prisma.FieldRef<"Settler", 'String'>
  readonly health_pain: Prisma.FieldRef<"Settler", 'Int'>
  readonly health_infection: Prisma.FieldRef<"Settler", 'Int'>
  readonly health_digestion: Prisma.FieldRef<"Settler", 'Int'>
  readonly health_consciousness: Prisma.FieldRef<"Settler", 'Int'>
  readonly health_sanity: Prisma.FieldRef<"Settler", 'Int'>
  readonly capacity_breathing: Prisma.FieldRef<"Settler", 'Int'>
  readonly capacity_eating: Prisma.FieldRef<"Settler", 'Int'>
  readonly capacity_hearing: Prisma.FieldRef<"Settler", 'Int'>
  readonly capacity_moving: Prisma.FieldRef<"Settler", 'Int'>
  readonly capacity_seeing: Prisma.FieldRef<"Settler", 'Int'>
  readonly needs_thirst: Prisma.FieldRef<"Settler", 'Int'>
  readonly needs_hunger: Prisma.FieldRef<"Settler", 'Int'>
  readonly needs_sleep: Prisma.FieldRef<"Settler", 'Int'>
  readonly needs_rest: Prisma.FieldRef<"Settler", 'Int'>
  readonly needs_social: Prisma.FieldRef<"Settler", 'Int'>
  readonly attr_strength: Prisma.FieldRef<"Settler", 'Int'>
  readonly attr_constitution: Prisma.FieldRef<"Settler", 'Int'>
  readonly attr_dexterity: Prisma.FieldRef<"Settler", 'Int'>
  readonly attr_perception: Prisma.FieldRef<"Settler", 'Int'>
  readonly attr_intelligence: Prisma.FieldRef<"Settler", 'Int'>
  readonly attr_wisdom: Prisma.FieldRef<"Settler", 'Int'>
  readonly skill_digging: Prisma.FieldRef<"Settler", 'Int'>
  readonly skill_logging: Prisma.FieldRef<"Settler", 'Int'>
  readonly skill_mining: Prisma.FieldRef<"Settler", 'Int'>
  readonly skill_foraging: Prisma.FieldRef<"Settler", 'Int'>
  readonly skill_fishing: Prisma.FieldRef<"Settler", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Settler", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Settler", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Settler findUnique
 */
export type SettlerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Settler
   */
  select?: Prisma.SettlerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Settler
   */
  omit?: Prisma.SettlerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlerInclude<ExtArgs> | null
  /**
   * Filter, which Settler to fetch.
   */
  where: Prisma.SettlerWhereUniqueInput
}

/**
 * Settler findUniqueOrThrow
 */
export type SettlerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Settler
   */
  select?: Prisma.SettlerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Settler
   */
  omit?: Prisma.SettlerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlerInclude<ExtArgs> | null
  /**
   * Filter, which Settler to fetch.
   */
  where: Prisma.SettlerWhereUniqueInput
}

/**
 * Settler findFirst
 */
export type SettlerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Settler
   */
  select?: Prisma.SettlerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Settler
   */
  omit?: Prisma.SettlerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlerInclude<ExtArgs> | null
  /**
   * Filter, which Settler to fetch.
   */
  where?: Prisma.SettlerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Settlers to fetch.
   */
  orderBy?: Prisma.SettlerOrderByWithRelationInput | Prisma.SettlerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Settlers.
   */
  cursor?: Prisma.SettlerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Settlers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Settlers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Settlers.
   */
  distinct?: Prisma.SettlerScalarFieldEnum | Prisma.SettlerScalarFieldEnum[]
}

/**
 * Settler findFirstOrThrow
 */
export type SettlerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Settler
   */
  select?: Prisma.SettlerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Settler
   */
  omit?: Prisma.SettlerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlerInclude<ExtArgs> | null
  /**
   * Filter, which Settler to fetch.
   */
  where?: Prisma.SettlerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Settlers to fetch.
   */
  orderBy?: Prisma.SettlerOrderByWithRelationInput | Prisma.SettlerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Settlers.
   */
  cursor?: Prisma.SettlerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Settlers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Settlers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Settlers.
   */
  distinct?: Prisma.SettlerScalarFieldEnum | Prisma.SettlerScalarFieldEnum[]
}

/**
 * Settler findMany
 */
export type SettlerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Settler
   */
  select?: Prisma.SettlerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Settler
   */
  omit?: Prisma.SettlerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlerInclude<ExtArgs> | null
  /**
   * Filter, which Settlers to fetch.
   */
  where?: Prisma.SettlerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Settlers to fetch.
   */
  orderBy?: Prisma.SettlerOrderByWithRelationInput | Prisma.SettlerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Settlers.
   */
  cursor?: Prisma.SettlerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Settlers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Settlers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Settlers.
   */
  distinct?: Prisma.SettlerScalarFieldEnum | Prisma.SettlerScalarFieldEnum[]
}

/**
 * Settler create
 */
export type SettlerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Settler
   */
  select?: Prisma.SettlerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Settler
   */
  omit?: Prisma.SettlerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlerInclude<ExtArgs> | null
  /**
   * The data needed to create a Settler.
   */
  data: Prisma.XOR<Prisma.SettlerCreateInput, Prisma.SettlerUncheckedCreateInput>
}

/**
 * Settler createMany
 */
export type SettlerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Settlers.
   */
  data: Prisma.SettlerCreateManyInput | Prisma.SettlerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Settler createManyAndReturn
 */
export type SettlerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Settler
   */
  select?: Prisma.SettlerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Settler
   */
  omit?: Prisma.SettlerOmit<ExtArgs> | null
  /**
   * The data used to create many Settlers.
   */
  data: Prisma.SettlerCreateManyInput | Prisma.SettlerCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Settler update
 */
export type SettlerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Settler
   */
  select?: Prisma.SettlerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Settler
   */
  omit?: Prisma.SettlerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlerInclude<ExtArgs> | null
  /**
   * The data needed to update a Settler.
   */
  data: Prisma.XOR<Prisma.SettlerUpdateInput, Prisma.SettlerUncheckedUpdateInput>
  /**
   * Choose, which Settler to update.
   */
  where: Prisma.SettlerWhereUniqueInput
}

/**
 * Settler updateMany
 */
export type SettlerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Settlers.
   */
  data: Prisma.XOR<Prisma.SettlerUpdateManyMutationInput, Prisma.SettlerUncheckedUpdateManyInput>
  /**
   * Filter which Settlers to update
   */
  where?: Prisma.SettlerWhereInput
  /**
   * Limit how many Settlers to update.
   */
  limit?: number
}

/**
 * Settler updateManyAndReturn
 */
export type SettlerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Settler
   */
  select?: Prisma.SettlerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Settler
   */
  omit?: Prisma.SettlerOmit<ExtArgs> | null
  /**
   * The data used to update Settlers.
   */
  data: Prisma.XOR<Prisma.SettlerUpdateManyMutationInput, Prisma.SettlerUncheckedUpdateManyInput>
  /**
   * Filter which Settlers to update
   */
  where?: Prisma.SettlerWhereInput
  /**
   * Limit how many Settlers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Settler upsert
 */
export type SettlerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Settler
   */
  select?: Prisma.SettlerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Settler
   */
  omit?: Prisma.SettlerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlerInclude<ExtArgs> | null
  /**
   * The filter to search for the Settler to update in case it exists.
   */
  where: Prisma.SettlerWhereUniqueInput
  /**
   * In case the Settler found by the `where` argument doesn't exist, create a new Settler with this data.
   */
  create: Prisma.XOR<Prisma.SettlerCreateInput, Prisma.SettlerUncheckedCreateInput>
  /**
   * In case the Settler was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SettlerUpdateInput, Prisma.SettlerUncheckedUpdateInput>
}

/**
 * Settler delete
 */
export type SettlerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Settler
   */
  select?: Prisma.SettlerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Settler
   */
  omit?: Prisma.SettlerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlerInclude<ExtArgs> | null
  /**
   * Filter which Settler to delete.
   */
  where: Prisma.SettlerWhereUniqueInput
}

/**
 * Settler deleteMany
 */
export type SettlerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Settlers to delete
   */
  where?: Prisma.SettlerWhereInput
  /**
   * Limit how many Settlers to delete.
   */
  limit?: number
}

/**
 * Settler without action
 */
export type SettlerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Settler
   */
  select?: Prisma.SettlerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Settler
   */
  omit?: Prisma.SettlerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlerInclude<ExtArgs> | null
}
